object Dep {

    const val composeVersion = "1.0.5"
    const val kotlinVersion = "1.5.31"
    const val gradle = "7.0.3"
    const val hiltCoreVersion = "2.36"
    const val hiltVersion = "1.0.0"
    const val hiltComposeNavigationVersion = "1.0.0-alpha03"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.4.0"
    const val activityComposeVersion = "1.3.0"
    const val constraintLayoutComposeVersion = "1.0.0-rc02"
    const val pagingComposeVersion = "1.0.0-alpha14"
    const val timberVersion = "4.7.1"
    const val gsonVersion = "2.8.7"
    const val accompanistVersion = "0.16.1"
    const val roomVersion = "2.3.0-beta02"
    const val coilVersion = "1.3.1"
    const val retrofitVersion = "2.9.0"
    const val loggingInterceptor = "4.9.1"
}